name: Jira issue from TODO
description: Create Jira issue for TODO comments
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  project:
    description: Key of the project
    required: true
  issuetype:
    description: "Type of the issue to be created. Example: 'Incident'"
    required: true
  description:
    description: Issue description
    required: false
outputs:
  issues:
    description: Well-formed JSON array containing keys of all newly created issues
runs:
  using: 'node12'
  main: './dist/index.js'
